global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'analytics'
    static_configs:
      - targets: ['analytics:9091']
        labels:
          service: 'analytics'
          component: 'context8'

  - job_name: 'mcp'
    static_configs:
      - targets: ['mcp:9092']
        labels:
          service: 'mcp'
          component: 'context8'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
